### ISSUE TITLE
Easy way to update decorators on line change

### ISSUE THREAD

**Issue by dgorissen** [bbecquet/Leaflet.PolylineDecorator#13]
Thanks for a very useful little lib.

I regularly need to update my polylines with new coordinates. I do this by calling line.setLatLngs(<new coords>). 

How would I update the associated decorators (in my case arrow heads) without creating new ones and throwing away the old ones?

**Comment by rluvaton** [comment]
Is it possible to bind the polyline position to the arrow position too?
