### ISSUE TITLE
Polyline draw incorrectly

### ISSUE THREAD

**Issue by hemanta25** [bbecquet/Leaflet.PolylineDecorator#29]
I am using map box and leaflet for drawing polyline , But when draw the polyline some points to be draw incorrectly as per below latitude longitude :

[-33.3333333333333	-165.75,
-31.6166666666667	-169.6,
-29.9333333333333	-173.683333333333,
-28.4	-177.466666666667,
-26.3	178.466666666667,
-23.85	174.216666666667,
-21.4833333333333	170.366666666667,
-18.9833333333333	166.916666666667]

Please suggest some solution. Some issue related to grenwitch. How to draw correct polyline.

**Comment by bbecquet** [comment]
Hi.
It's not related to my plugin but to the way Leaflet (and then Mapbox.js) deals with polylines crossing the 180th meridian (not Greenwhich).
You can see these two issues for reference:
https://github.com/mapbox/mapbox.js/issues/360
https://github.com/Leaflet/Leaflet/issues/82

The easiest workaround for these cases is to add 360 to the negative longitudes. The resulting values are not geographically valid, but Leaflet will "wrap" them correctly around the meridian.
