### ISSUE TITLE
Leaflet 1.0

### ISSUE THREAD

**Issue by bardu** [bbecquet/Leaflet.PolylineDecorator#36]
Leaflet 1.0 is breaking your plugin, are there any plans to upgrade?

**Comment by bbecquet** [comment]
Hi! Can you please explain how it breaks for you, and especially:
 * are you using bower or the version from the `master` branch?
 * what specific code broke?

The current version in the `master` branch is targeted at Leaflet 0.8+ (which is very similar to the 1.0 version) and according to my tests it is still working with Leaflet 1.0.0-b1.

There is only one version available through bower yet, which is for the latest stable release of Leaflet (0.7.3) and is not compatible with Leaflet 1.0.0-b1.

**Comment by bardu** [comment]
Sorry, I had the older version, the current master branch works.
