### ISSUE TITLE
Rotated markers are shifted with Leaflet 1.0 beta

### ISSUE THREAD

**Issue by Szecskkaa** [bbecquet/Leaflet.PolylineDecorator#38]
I tried to use the leaflet polyline decorator with leaflet 1.0 beta, but I ran into a problem. When I set rotate: true, the markers are not on the polylines, but when I use the leaflet 0.7.3, the markers are on the polylines. (See the two pictures (first: 0.7.3, second: 1.0 beta))

![stable](https://cloud.githubusercontent.com/assets/13817934/9292975/3637a934-4416-11e5-8bbf-242502f6807f.png)

![beta](https://cloud.githubusercontent.com/assets/13817934/9292976/38bfbfca-4416-11e5-8e24-3d1c3cd488e7.png)

I use the same code, the difference is the version of leaflet.

var map = L.map('map').setView([52, -11.0], 5);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
attribution: '© OpenStreetMap contributors'
}).addTo(map);

var markerLine = L.polyline([[58.44773, -28.65234], [52.9354, -23.33496], [53.01478, -14.32617], [58.1707, -10.37109], [59.68993, -0.65918]], {}).addTo(map);

var pathPattern = L.polylineDecorator(markerLine,{
patterns: [
{ offset: '10px', repeat: '100px', symbol: L.Symbol.marker({rotate: true, markerOptions: {
icon: L.icon({
iconUrl: 'images/marker-icon.png',
iconSize: [11, 17]
})
}})}
]
}).addTo(map);

**Comment by bbecquet** [comment]
Thanks for filing this issue.

This is actually a bug, coming from the different way Leaflet 0.7.x and 1.0 handle CSS transforms applied to markers, especially the `transform-origin` rule.

As I took so long to reply (I'm very sorry), you've probably found a workaround by now. But in any case, I should be able to fix it quickly now.

**Comment by bbecquet** [comment]
This should be ok now with the latest version and Leaflet 1.0b.
