### ISSUE TITLE
is it possible to change the L.Symbol.arrowHead color?

### ISSUE THREAD

**Issue by travisslack** [bbecquet/Leaflet.PolylineDecorator#53]
I've tried specifying a color in the pathoptions and elsewhere but no luck. im looking to make a polyline the same width as the symbol so the arrow head fits nicely inside the line but with a different color. 

thanks

**Comment by wishinghand** [comment]
@unknownids If you figured this out, please post here what you did.

**Comment by kras95** [comment]
**color** parameter inside the pathOptions parameters. Easy guess.
`L.Symbol.arrowHead({ pathOptions: { color: '#ffffff' } })`

**Comment by hamza-sabri5** [comment]
when using this method I am not able to use pixelSize to control the size of the created arrow, what can I give pathOptions to do so?

**Comment by hamza-sabri5** [comment]
to solve this I had to grap the ref of it using css and then change the color their
to do so use this code
/*code : */
.leaflet-interactive[stroke = "none"]{
  fill:black;
  fill-opacity: 1;
}
you can then change the color of it and other stuff like you are editing any other HTML element

**Comment by Pawandeep-Kaur-Betz** [comment]
What if we have to change it dynamically as in this question: [here](https://stackoverflow.com/questions/72815727/change-the-color-of-the-l-symbol-arrowhead-in-typescript-leaflet)
