### ISSUE TITLE
Change decorator on a polyline

### ISSUE THREAD

**Issue by powpowland** [bbecquet/Leaflet.PolylineDecorator#59]
Hello,
I want to change decoration on a polyline with the zoom.

```
if (map.getZoom() == 15) {
               poly.setStyle({weight: 3});
				L.polylineDecorator(poly,{setPatterns: [{offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 15, pathOptions: {color:"red'",fillOpacity: 1, weight: 0}})}]}).addTo(map);
            }
if (map.getZoom() == 14) {
               poly.setStyle({weight: 3});
				L.polylineDecorator(poly,{setPatterns: [{offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 5, pathOptions: {color:"blue'",fillOpacity: 1, weight: 0}})}]}).addTo(map);
            }
```

But it doesn't change the decoration, it add a decoration above.

could you help me ?

thank you

**Comment by powpowland** [comment]
my code is that, patterns instead of setPatterns : 

```
if (map.getZoom() == 15) {
               poly.setStyle({weight: 3});
				L.polylineDecorator(poly,{setPatterns: [{offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 15, pathOptions: {color:"red'",fillOpacity: 1, weight: 0}})}]}).addTo(map);
            }
if (map.getZoom() == 14) {
               poly.setStyle({weight: 3});
				L.polylineDecorator(poly,{setPatterns: [{offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 5, pathOptions: {color:"blue'",fillOpacity: 1, weight: 0}})}]}).addTo(map);
            }
```

**Comment by powpowland** [comment]
my code is that, patterns instead of setPatterns :

if (map.getZoom() == 15) {
               poly.setStyle({weight: 3});
				L.polylineDecorator(poly,{patterns: [{offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 15, pathOptions: {color:"red'",fillOpacity: 1, weight: 0}})}]}).addTo(map);
            }
if (map.getZoom() == 14) {
               poly.setStyle({weight: 3});
				L.polylineDecorator(poly,{patterns: [{offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 5, pathOptions: {color:"blue'",fillOpacity: 1, weight: 0}})}]}).addTo(map);
            }

**Comment by bbecquet** [comment]
Hi!
You have to save the instance of the PolylineDecorator after instantiation, then call the `setPatterns` method on it. Like that:
```js
var decorator = L.polylineDecorator(poly, {patterns: [ /* your initial patterns */ ]}).addTo(map);
...
if (map.getZoom() == 15) {
   poly.setStyle({weight: 3});
   poly.setPatterns([
      {offset: 25, repeat: 100, symbol: L.Symbol.arrowHead({pixelSize: 15, pathOptions: {color:"red'", fillOpacity: 1, weight: 0}})}
   ]);
}
```
Please tell me if this works for you :)

**Comment by powpowland** [comment]
thank you but I have en error with that code : 
`poly.setPatterns is not a function`

**Comment by bbecquet** [comment]
Sorry, should have written `decorator` in the if block instead of `poly`. Will edit my example.

**Comment by powpowland** [comment]
perfect!!!

merci à toi
