### ISSUE TITLE
Create user defined Symbol or pass user defined SVG Pattern in patterns

### ISSUE THREAD

**Issue by nithyanv** [bbecquet/Leaflet.PolylineDecorator#62]
Is there an example on how we may create our own user defined symbols (to be used with L.Symbol)? Also, where can I find the list of predefined symbols in PolylineDecorator? Currently, I wished to have a double line. We have tried using small image of two lines repeated and that works great. But we have would like to be able to change the color. Creating multiple images(different colors) would not efficient or a configurable option. Using a user defined svg pattern would also help. We would be able to set the colors on the page.

**Comment by bbecquet** [comment]
Hi! Sorry this part of the plugin is not well (at all) documented.

If you want to know the predefined symbols, you can look at the code, in the `L.Symbol.js` file. You'll also see what a custom class should provide if you want to use it as a symbol. Basically, you need to implement the `buildSymbol` function, which must return an instance of `L.Layer`. As a `LayerGroup` is a `Layer` itself, you can return composite symbols, which may be useful for your double line. The color you want to change can be an option of your custom symbol class.

As an alternative, if you don't need complex interaction on the symbols, you can give a try to this other plugin: https://github.com/makinacorpus/Leaflet.TextPath
It uses SVG pattern only and may fit your use case. It will also be much better performance wise.
