### ISSUE TITLE
Error when passing < 2 points

### ISSUE THREAD

**Issue by Techn1x** [bbecquet/Leaflet.PolylineDecorator#64]
Obviously, it's pretty silly to give the polyline decorator < 2 points, but rather than just gracefully not doing anything when given this, it errors and leaflet crashes

Pretty small issue because I can just put a check in my js to ensure this never happens, but I believe when a standard polyline is given < 2 points it doesn't crash, so perhaps the same should occur with this addon?

The error I get is something like
```
TypeError: Cannot read property 'predecessor' of null at Object.projectPatternOnPointPath (vendor-4da3fd3….js:5579)
at Object.projectPatternOnPath (vendor-4da3fd3….js:5575)
at n._getDirectionPoints (vendor-4da3fd3….js:5565)
at n._drawPattern (vendor-4da3fd3….js:5566)
at n._draw (vendor-4da3fd3….js:5567)
at n.onAdd (vendor-4da3fd3….js:5560)
at n._layerAdd (vendor-4da3fd3….js:5207)
at n.whenReady (vendor-4da3fd3….js:5118)
at n.addLayer (vendor-4da3fd3….js:5209)
at n.addLayer (vendor-4da3fd3….js:5219)
```

Specifically, the error occurs here;
https://github.com/bbecquet/Leaflet.PolylineDecorator/blob/188ef17dadf22b562081d2400d4008bc216f952e/src/L.PolylineDecoratorUtil.js#L64

`previous` gets set to `interpolateOnPointPath` which returns null when given < 2 points. And then later `previous.predecessor` is attempted to be accessed, causing the error

Thoughts?

**Comment by bbecquet** [comment]
You're right, that's a real bug. And not small IMO if it results in a crash. But easy to fix :) I'll do it quickly when I have a bit of time.

**Comment by bbecquet** [comment]
Ok, this should be fixed in the new version I pushed (v1.3.0). Let me know :)

**Comment by Techn1x** [comment]
Fantastic, thanks! I'll test it out later today

**Comment by Techn1x** [comment]
Thanks @bbecquet it works great. Just so you're aware, we're using it as an ember-leaflet addon here
https://github.com/transitland/ember-leaflet-polyline-decorator
