### ISSUE TITLE
Error when instanciating a PolylineDecorator on a Polyline array

### ISSUE THREAD

**Issue by marcagba** [bbecquet/Leaflet.PolylineDecorator#68]
What:
Instanciating PolylineDecorator on a Polyline array result on an error.

Why:
This is due to a typo error in the internal function _initPaths in charge of harmonizing the paths given to the PolylineDecorator.

A PR is coming to fix this issue.

**Comment by bbecquet** [comment]
Hi!
Thanks a lot for spotting it and proposing a fix. And sorry I've taken so damn long to look at it. I'm gonna merge the PR. And it also motivated me to refactor this part completely, as it's by far the ugliest and untested part remaining.
Thanks again.

**Comment by marcagba** [comment]
You're welcome ;)
